[project]
name = "gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=2.14.4",
    "dspy>=2.5.42",
    "langchain-community>=0.3.14",
    "openai>=1.58.1",
    "qdrant-client>=1.12.2",
    "smolagents>=1.0.0",
    "torch>=2.5.1",
    "transformers>=4.47.1",
    "vllm>=0.1.2",
]
