[project]
name = "gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.58.1",
    "qdrant-client>=1.12.2",
    "torch>=2.5.1",
    "transformers>=4.47.1",
]
